--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 16.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: flyway_schema_history; Type: TABLE; Schema: public; Owner: petruho
--

CREATE TABLE public.flyway_schema_history (
    installed_rank integer NOT NULL,
    version character varying(50),
    description character varying(200) NOT NULL,
    type character varying(20) NOT NULL,
    script character varying(1000) NOT NULL,
    checksum integer,
    installed_by character varying(100) NOT NULL,
    installed_on timestamp without time zone DEFAULT now() NOT NULL,
    execution_time integer NOT NULL,
    success boolean NOT NULL
);


ALTER TABLE public.flyway_schema_history OWNER TO petruho;

--
-- Name: t_item; Type: TABLE; Schema: public; Owner: petruho
--

CREATE TABLE public.t_item (
    price numeric(38,2),
    amount bigint,
    id bigint NOT NULL,
    subject character varying(255)
);


ALTER TABLE public.t_item OWNER TO petruho;

--
-- Name: t_item_id_seq; Type: SEQUENCE; Schema: public; Owner: petruho
--

ALTER TABLE public.t_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.t_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: t_item_seq; Type: SEQUENCE; Schema: public; Owner: petruho
--

CREATE SEQUENCE public.t_item_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.t_item_seq OWNER TO petruho;

--
-- Name: t_user; Type: TABLE; Schema: public; Owner: petruho
--

CREATE TABLE public.t_user (
    id bigint NOT NULL,
    email character varying(30) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255),
    username character varying(50) NOT NULL,
    CONSTRAINT t_user_role_check CHECK (((role)::text = ANY (ARRAY[('USER'::character varying)::text, ('ADMIN'::character varying)::text])))
);


ALTER TABLE public.t_user OWNER TO petruho;

--
-- Name: t_user_id_seq; Type: SEQUENCE; Schema: public; Owner: petruho
--

ALTER TABLE public.t_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.t_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: flyway_schema_history; Type: TABLE DATA; Schema: public; Owner: petruho
--

COPY public.flyway_schema_history (installed_rank, version, description, type, script, checksum, installed_by, installed_on, execution_time, success) FROM stdin;
\.


--
-- Data for Name: t_item; Type: TABLE DATA; Schema: public; Owner: petruho
--

COPY public.t_item (price, amount, id, subject) FROM stdin;
15000.00	2	1	Computer
7000.00	3	2	Headphones
10000.00	4	3	Telephone
5000.00	1	4	Fen
\.


--
-- Data for Name: t_user; Type: TABLE DATA; Schema: public; Owner: petruho
--

COPY public.t_user (id, email, password, role, username) FROM stdin;
2	petruho@mail.ru	$2a$10$..pMdUDK6FIwAMCZkR6rGeFHft03LB10FYTJEPf/lsX1uJLHsN/1i	USER	petruho
4	petruho2019@mail.ru	$2a$10$n0W0RionVuroPwibTMi1c.NzuTuUD7p6TytHcTktVIxatCFYPgS7O	USER	petruho2019
5	vlad@mail.ru	$2a$10$D1FSpURL..t.GwqJspAkJOebgZAULi/V2Gupf633iNIDhcvrIAQ2y	USER	vlad
\.


--
-- Name: t_item_id_seq; Type: SEQUENCE SET; Schema: public; Owner: petruho
--

SELECT pg_catalog.setval('public.t_item_id_seq', 4, true);


--
-- Name: t_item_seq; Type: SEQUENCE SET; Schema: public; Owner: petruho
--

SELECT pg_catalog.setval('public.t_item_seq', 51, true);


--
-- Name: t_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: petruho
--

SELECT pg_catalog.setval('public.t_user_id_seq', 18, true);


--
-- Name: flyway_schema_history flyway_schema_history_pk; Type: CONSTRAINT; Schema: public; Owner: petruho
--

ALTER TABLE ONLY public.flyway_schema_history
    ADD CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank);


--
-- Name: t_item t_item_pkey; Type: CONSTRAINT; Schema: public; Owner: petruho
--

ALTER TABLE ONLY public.t_item
    ADD CONSTRAINT t_item_pkey PRIMARY KEY (id);


--
-- Name: t_user t_user_pkey; Type: CONSTRAINT; Schema: public; Owner: petruho
--

ALTER TABLE ONLY public.t_user
    ADD CONSTRAINT t_user_pkey PRIMARY KEY (id);


--
-- Name: flyway_schema_history_s_idx; Type: INDEX; Schema: public; Owner: petruho
--

CREATE INDEX flyway_schema_history_s_idx ON public.flyway_schema_history USING btree (success);


--
-- PostgreSQL database dump complete
--

