create table t_item
    (price numeric(38,2),
    amount bigint,
    id bigint generated by default as identity,
    subject varchar(2048),
    primary key (id));

create table t_user
    (id bigint generated by default as identity,
     email varchar(2048) not null,
     password varchar(2048) not null,
     role varchar(2048) check (role in ('USER','ADMIN')),
     username varchar(2048) not null,
     primary key (id))